name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  Build-Test:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [macOS-latest,windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Test
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release

